---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 5cd438cb8a91e0b17b5a91821b94f03e3ef01974
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      provider: fabric8
      project: mobile
      version: 1.0-SNAPSHOT
      group: amazon
    name: mobile
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: mobile
      provider: fabric8
      group: amazon
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 5cd438cb8a91e0b17b5a91821b94f03e3ef01974
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=mobile&var-version=1.0-SNAPSHOT
    labels:
      provider: fabric8
      project: mobile
      version: 1.0-SNAPSHOT
      group: amazon
    name: mobile
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: mobile
        provider: fabric8
        group: amazon
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 5cd438cb8a91e0b17b5a91821b94f03e3ef01974
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=mobile&var-version=1.0-SNAPSHOT
        labels:
          provider: fabric8
          project: mobile
          version: 1.0-SNAPSHOT
          group: amazon
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: amazon/mobile:snapshot-210204-142426-0950
          imagePullPolicy: IfNotPresent
          name: java-exec
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
